version: '3'
services:
  gpu:
    build: ./docker
    # please set unique container name
    container_name: sas
    # please set unique port number (49152â€“65535)
    ports:
      - "51115:22"
    volumes:
      - ./volume:/mnt
    tty: true
    shm_size: '2gb'
    entrypoint: "/bin/bash /cmd.sh"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
